name: Windows Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Build
        run: |
          g++ -o main.exe main.cpp

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: main.exe
          path: main.exe
