name: Build y ejecutar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout el código
        uses: actions/checkout@v2

      - name: Compilar y ejecutar
        run: |
          cmake .
          cmake --build . --target Sandbox
          ./Sandbox