name: Build and Export

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libglfw3-dev libglew-dev libglm-dev

    - name: Configure GLFW
      run: |
        mkdir -p ~/libraries/glfw
        cd ~/libraries/glfw
        wget https://github.com/glfw/glfw/archive/refs/tags/3.3.8.zip
        unzip 3.3.8.zip
        cd glfw-3.3.8
        cmake .
        sudo make install

    - name: Create build directory
      run: mkdir build

    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build the project
      run: cmake --build build --config Release

    - name: Archive the build
      uses: actions/upload-artifact@v3
      with:
        name: sandbox-game
        path: build/
