name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SFML
      run: |
        sudo apt-get update
        sudo apt-get install -y libsfml-dev
        
    - name: Configure CMake
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Package Windows
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: SandboxGame-Windows
        path: SandboxGame-Windows.zip
        if-no-files-found: error
        retention-days: 30
        compression-level: 6
        overwrite: true
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: SandboxGame-Windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
