name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.12' 
            
      - name: Install dependencies
        run: |
          pip install pygame PyOpenGL PyOpenGL-accelerate

      - name: Build and deploy
        run: |
          python setup.py bdist_wheel
          python -m twine upload dist/*