# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SFML
      run: |
        choco install -y sfml
        echo "SFML_ROOT=$env:PROGRAMFILES\SFML" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
    
    - name: Build
      run: |
        g++ -I$env:SFML_ROOT\include -L$env:SFML_ROOT\lib -o sandbox.exe main.cpp -lsfml-graphics -lsfml-window -lsfml-system
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sandbox-windows
        path: sandbox.exe
