name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SFML
      run: |
        choco install -y sfml
        
    - name: Configure CMake
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Package
      run: |
        cd build
        Compress-Archive -Path SandboxGame.exe -DestinationPath ../SandboxGame-Windows.zip
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: SandboxGame-Windows
        path: SandboxGame-Windows.zip
        if-no-files-found: error
        retention-days: 30
        compression-level: 6
        overwrite: true
      
