name: Windows Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MinGW
        uses: mingw-w64/setup@v1
        with:
          architecture: x86_64

      - name: Build
        run: |
          g++ -o main.exe main.cpp

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: main.exe
          path: main.exe
