name: Windows

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cmake --build . --target install

      - name: Compile and run
        run: |
          cmake --build . --target sandbox
          .\bin\sandbox.exe