name: Build and Export to Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyglet numpy pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --name sandbox_game main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sandbox-game
        path: dist/sandbox_game.exe

