name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SFML
      run: |
        sudo apt-get update
        sudo apt-get install -y libsfml-dev
        
    - name: Configure CMake
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Package
      run: |
        cd build
        7z a ../SandboxGame.zip .
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: SandboxGame.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
